version: "3"
services:
  # db:
  #   restart: always
  #   image: postgres:latest
  #   command: "--innodb_use_native_aio=0"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - /var/lib/postgresql/10/main
  app:
    env_file: .env
    build: .
    ports:
      - "2000:2000"
  #   depends_on:
  #     - db
